DEEPDIVE-BookJuck-BookJuck/BookJuck-BookJuck

package-lock.json, src/app/page.tsx, src/app/types/mypageHome/bookTypes.ts, src/components/BookCard.tsx
=> fix:타입오류 수정

src/app/(with-header)/mylibrary/(detail)/[id]/page.tsx, src/components/LibraryBookItem.tsx
> ex) #14
>  - next/image에 width, height 누락으로 인한 런타임 에러 수정
=> fix : next/image 필수 속성 누락 런타임 에러 수정 (#14)

src/app/(without-header)/auth/login/page.tsx, src/lib/fetchWithAuth.ts
> #16
> unexpected any 타입 에러 수정
=> fix: type 오류 수정

package-lock.json, package.json, src/app/(without-header)/auth/login/page.tsx
> #21
> 로그인 버튼 중복 클릭 방지 기능 추가
> 커스텀 검증 로직 추가 및 에러 메시지 추가
> 유효성 검사 통과 시에만 폼 제출 가능
=> feat: 로그인 페이지 기능 구현

src/app/(without-header)/auth/login/page.tsx, src/components/Header.tsx
> #25
> 헤더 디자인 개선 (아이콘 추가)
> 로그인 시 이메일 정규식을 활용하여 엄격하게 체크하도록 개선
> 로그인 시 비밀번호 자릿수 검사 기능 추가
=> feat: 공용 레이아웃 디자인 개선 및 로그인 유효성 검사 기능 수정

src/app/(with-header)/@modal/(.)profile/page.tsx, src/app/(with-header)/@modal/default.tsx, src/app/(with-header)/layout.tsx, src/app/(with-header)/my-page/page.tsx, src/app/(with-header)/profile/_components/button.tsx, src/app/(with-header)/profile/_components/profile-item.tsx, src/app/(with-header)/profile/page.tsx, src/common/modal.tsx
=> feat: 회원 정보 수정 퍼블리싱 및 모달 구현

src/app/(without-header)/auth/_types/index.ts, src/app/(without-header)/auth/log-in/page.tsx, src/app/(without-header)/auth/sign-up/page.tsx, src/lib/auth.ts
> #36
> sign-up 페이지 퍼블리싱
> 회원가입 유효성 검사 로직 구현
=> feat: 회원가입 페이지 UI 및 기능 구현

src/lib/fetch-with-auth.ts
> #40 
> 서버 / 클라이언트 환경에 따라 API_URL 분기 처리
=> feat: API_URL 분기 처리

src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx, src/app/(with-header)/(protected)/my-page/_types/index.ts, src/app/(with-header)/(protected)/my-page/page.tsx
> #51 
> 최근 읽은 책 컴포넌트 API 연동
- 현재 토큰이 없어 에러 발생
- 임시로 토큰을 하드코딩하여 동작 여부 확인 완료
=> feat: 최근 읽은 책 컴포넌트 API 연동

src/app/(with-header)/(protected)/my-library/(list)/page.tsx
> ex) #62
> my-library페이지 fetchBooks 함수 의존성 누락 경고 수정
=> fix: my-library페이지 fetchBooks 함수 의존성 누락 경고 수정(#62)

src/app/(with-header)/page.tsx, src/app/_components/book-card.tsx, src/app/api/aladin-list/route.ts
> #56
> List API 를 연동하여 베스트 셀러 섹션 구현 완료
=> chore:베스트셀러 API 연결 및 섹션 구현

src/app/(with-header)/(protected)/my-page/page.tsx, src/app/(without-header)/auth/log-in/page.tsx, src/lib/fetch-with-auth-server.ts, src/lib/fetch-with-auth.ts, src/store/auth-store.ts
> #59 
> 로그인 상태 저장 기능 구현
> 인증 토큰 저장 방식 개선 및 그에 따른 my-page/page.tsx 파일 참조 수정
=> feat: 로그인 상태 및 토큰 저장 방식 개선

src/common/common-header.tsx, src/lib/auth.ts
> #72
> 환경 변수 수정
> 로그아웃 기능 구현
> 헤더 메뉴 텍스트 한글화
=> feat: 환경 변수 수정 및 로그아웃 기능 구현

src/app/(with-header)/(protected)/my-page/_components/graph.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx, src/app/(with-header)/(protected)/my-page/_components/tag-graph.tsx, src/app/(with-header)/(protected)/my-page/page.tsx, src/app/(with-header)/layout.tsx
=> style: mypage 반응형 레이아웃 구현

src/common/common-header.tsx, src/lib/auth.ts
> #74
> lib/auth.ts require -> import 사용
> 공용 헤더 반응형 구현
=> feat: 공용 헤더 반응형 구현 및 코드 스타일 통일

src/app/(with-header)/(protected)/my-library/(detail)/[id]/page.tsx, src/app/(with-header)/(protected)/my-library/(list)/page.tsx, src/app/(with-header)/(protected)/my-library/_components/_detail/book-thumbnail.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/book-thumbnail.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/tag-list.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/book-card-skeleton.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/box-skeleton.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/detail-page-skeleton.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/list-page-skeleton.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/search-skeleton.tsx
> ex) #86 
> my-library 스켈레톤 UI 추가
> my-library 북 카드 UI 수정
=> feat: my-library UI 수정(#86)

src/app/(with-header)/(protected)/my-page/_components/monthly-graph.tsx, src/app/(with-header)/(protected)/my-page/loading.tsx, src/app/(with-header)/(protected)/my-page/page.tsx
> #80 
> 마이페이지 API 호출 방식 변경 및 타이틀 변경
```
1차 측정: 1.242s
2차 측정: 1.307s
3차 측정: 1.400s
4차 측정: 1.654s
──────────────────
평균: 1.401s
```
```
1차 측정: 649.927ms (0.650s)
2차 측정: 630.33ms  (0.630s)
3차 측정: 534.428ms (0.534s)
4차 측정: 630.937ms (0.631s)
──────────────────────────────
평균: 611.4ms (0.611s)
```
- **평균 56.3% 빨라짐**
=> refactore: 마이페이지 API 호출 방식 변경 및 타이틀 변경

src/app/(with-header)/(protected)/layout.tsx
=> feat: Protected Route 활성화

src/app/(with-header)/(protected)/_types/index.ts, src/app/(with-header)/(protected)/my-library/(detail)/[id]/page.tsx, src/app/(with-header)/(protected)/my-library/(list)/layout.tsx, src/app/(with-header)/(protected)/my-library/(list)/page.tsx, src/app/(with-header)/(protected)/my-library/_components/_detail/book-thumbnail.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx, src/app/(with-header)/(protected)/my-page/_types/index.ts, src/app/(with-header)/(protected)/my-page/page.tsx, src/app/(with-header)/(protected)/profile/_components/profile-item.tsx, src/app/(with-header)/(protected)/profile/_types/index.ts
=> refactor: 중복타입 공통으로 분리

src/app/(with-header)/(protected)/my-library/(list)/layout.tsx
> ex) #103
> my-library 로그인되지 않은 경우 프로필 호출 방지
=> fix: my-library 로그인되지 않은 경우 프로필 호출 방지(#103)

src/app/(with-header)/layout.tsx, src/app/(without-header)/auth/layout.tsx, src/app/layout.tsx
> #107 
> 루트 레이아웃 위치 수정 및 스타일 수정
=> refactor: 루트 레이아웃 위치 수정 및 스타일 수정

src/app/(with-header)/(protected)/my-library/(detail)/[id]/page.tsx, src/app/(with-header)/(protected)/my-library/(list)/page.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/tag-list.tsx
> ex) #110 
> my-library 북카드 UI 수정 
> 독후감 내용이 비어있을 경우 수정,저장,삭제시 에러 처리 추가
=> feat: my-library 북카드 UI 수정 / 독후감 수정,저장,삭제시 에러 처리 추가

src/app/globals.css, src/app/not-found.tsx
> #100 
> 커스텀 스크롤바 적용 및 404 페이지 구현
=> feat: 커스텀 스크롤바 적용 및 404 페이지 구현

src/app/(with-header)/page.tsx, src/app/_components/book-card.tsx
> #122
> 모달 관련 수정 및 로그인 관련 오류 수정
=> fix: 모달 관련 수정 및 로그인 관련 오류 수정

src/app/(with-header)/(protected)/layout.tsx
> #129
> ProtectedLayout 내 router.replace 호출로 인한 렌더링 중 상태 업데이트 오류 해결
=> fix: 로그인 리디렉션 오류 해결

src/app/(with-header)/(protected)/_components/tag-list.tsx, src/app/(with-header)/(protected)/my-library/_components/_list/library-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx, src/app/(with-header)/(protected)/profile/_components/profile-item.tsx
=> feat: my-page UX 개선

src/app/(with-header)/(protected)/profile/_components/profile-item.tsx
=> feat: 닉네임 글자수 제한 설정

src/app/(without-header)/auth/_components/button.tsx, src/app/(without-header)/auth/_components/form-error.tsx, src/app/(without-header)/auth/log-in/page.tsx, src/app/(without-header)/auth/sign-up/page.tsx
> #125
> 인풋 에러 메시지 실시간으로 표시
에러 메시지 영역의 고정 높이를 지정하여 레이아웃 흔들림 방지
하나 이상의 인풋값이 비어있거나, 유효성 검사를 통과하지 못하면 submit 버튼 비활성화
=> feat: 로그인/회원가입 UI 개선

src/app/(with-header)/(protected)/my-page/_components/recent-book-item.tsx, src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
> #141 
> my-page 최근 읽은 책 라우팅 설정
=> feat: my-page 최근 읽은 책 라우팅 설정

src/common/common-header.tsx
> #143
> 모바일 사이드바 애니메이션 추가
로그아웃 컨펌 메시지 수정
=> feat: 모바일 사이드바 애니메이션 추가

src/app/(with-header)/(protected)/my-library/(detail)/[id]/view/page.tsx, src/app/(with-header)/(protected)/my-library/(list)/page.tsx, src/app/(with-header)/(protected)/my-library/_components/review-form.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/detail-page-skeleton.tsx, src/app/(with-header)/(protected)/my-library/_components/skeleton/list-page-skeleton.tsx
> ex) #145
> my-library 스켈레톤 UI 개선
=> style: my-library 스켈레톤 UI 개선(#145)

src/app/(with-header)/(main)/_components/book-card.tsx, src/app/(with-header)/(main)/page.tsx
=> fix:토큰 오류 수정 및 텍스트 수정

src/app/(with-header)/(main)/page.tsx, src/app/api/aladin-list/route.ts
=> feat:무한스크롤 구현

src/app/(with-header)/(main)/_components/skeleton/book-card-skeleton.tsx, src/app/(with-header)/(main)/_components/skeleton/box-skeleton.tsx, src/app/(with-header)/(main)/_components/skeleton/heading-skeleton.tsx, src/app/(with-header)/(main)/_components/skeleton/list-page-skeleton.tsx, src/app/(with-header)/(main)/_components/skeleton/search-skeleton.tsx, src/app/(with-header)/(main)/page.tsx
> #154
> main-page 스켈레톤 UI 구현 및 머지 충돌 해결
=> feat: main-page 스켈레톤 UI 구현 및 충돌 해결

src/app/(with-header)/(protected)/my-page/_components/graph.tsx, src/app/(with-header)/(protected)/my-page/_components/period-toggle.tsx, src/app/api/proxy/[...path]/route.ts
> #175 
> periodToggle 컴포넌트 생성
> 월별 그래프 컴포넌트에 기간 선택 기능 추가
- 요청 url에 파라미터 추가
=> feat: 월별 독서량 탭전환으로 6개월, 1년 독서기록 수 보기

src/app/(with-header)/(main)/page.tsx, src/app/api/aladin-list/route.ts, src/app/api/aladin-search/route.ts, src/common/modal.tsx
=> fix:무한스크롤 관련 오류 수정및 기능추가

src/app/api/auth/login/route.ts, src/app/api/auth/refresh/route.ts, src/lib/auth.ts, src/lib/fetch-with-auth-server.ts
=> chore: 불필요한 콘솔 로그 제거

src/app/(with-header)/(protected)/my-library/(list)/page.tsx
> ex) #189 
> - `fetchBooks(reset: boolean)` → `fetchBooks({ reset: boolean })`로 변경
> - 호출부 모두 일괄 수정
> - default value 설정 (`reset = false`)
> - `useEffect` 및 scroll 로직 등 종속된 부분 리팩토링 반영
=> Refactor: 내서재 fetchBooks 파라미터 구조 개선 (reset → 객체화)(#189)

src/app/(with-header)/(protected)/my-page/_components/recent-book.tsx
> #192 
> 최근 읽은 책 제목 변경 및 버튼 추가
=> refactor: 최근 읽은 책 제목 변경 및 버튼 추가

src/common/common-header.tsx
> ex) #193 
> 헤더 내비게이션 탭 pathname에 하위경로도 포함시키는 로직으로 변경
=>  Fix: 헤더 내비게이션 탭 활성화 로직 개선(#193)

src/app/layout.tsx, src/common/auto-logout-privider.tsx, src/hooks/use-auto-logout.ts
=> feat: 자동 로그아웃 기능 추가

src/common/common-header.tsx
> #198
> 홈 버튼 누를 시 페이지 새로고침 되도록 수정
=> fix: 공통 헤더의 홈 버튼 수정

src/app/(with-header)/(main)/_components/book-card.tsx
=> fix:버튼 색상 수정
